import {
  Box,
  Button,
  Card,
  FormControl,
  Grid,
  InputAdornment,
  OutlinedInput,
  Rating,
  styled,
  Typography,
} from '@mui/material';
import Head from 'next/head';

import ResponsiveNavBar from '../src/components/navbar';

import type { NextPage } from 'next';
import { Star } from '@mui/icons-material';
const ImgWrapper = styled('img')(
  ({ theme }) => `
    margin-right: ${theme.spacing(1)};
`,
);
const Home: NextPage = () => {
  return (
    <Grid sx={{ backgroundColor: '#F8CC5D' }}>
      <Head>
        <title>RatePunk Front End Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ResponsiveNavBar></ResponsiveNavBar>
      <Grid container direction={'row'} justifyContent={'space-around'}>
        <Grid item>
          <Card
            sx={{
              m: { xs: 2, sm: 2, md: 3, lg: 10 },
              backgroundColor: '#F8F4F9',
              border: '1px solid #1F343E',
              borderRadius: '16px',
              width: { lg: '544px', xs: 'auto' },
              height: '797px',
            }}>
            <Grid
              p={{ xs: 2, lg: 8 }}
              pb={5}
              container
              direction={'column'}
              justifyContent={'space-between'}>
              <Typography
                sx={{
                  font: 'normal normal normal 48px/72px Caveat Brush, cursive',

                  textTransform: 'uppercase',
                  color: '#1F343E',
                }}>
                REFER FRIENDS AND GET REWARDS
              </Typography>
            </Grid>
            <Grid
              p={{ xs: 2, lg: 8 }}
              pt={0}
              container
              direction={'column'}
              justifyContent={'space-between'}>
              <Typography
                sx={{
                  font: 'normal normal normal 20px/32px Noto Sans',

                  color: '#1F343E',
                }}>
                Refer your friends to us and earn hotel booking vouchers. We'll
                give you 1 coin for each friend that installs our extension.
                Minimum cash-out at 20 coins.
              </Typography>
            </Grid>

            <Grid
              p={{ xs: 2, lg: 8 }}
              pt={0}
              pb={2}
              container
              direction={'column'}
              justifyContent={'space-between'}>
              <Typography
                sx={{
                  font: 'normal normal normal 12px/24px Noto Sans',
                  color: '#ED6F82',
                  pb: 0.5,
                }}
                color={'error'}>
                Error State
              </Typography>
              <FormControl variant="outlined">
                <OutlinedInput
                  placeholder="Enter your email address"
                  sx={{
                    background: '#FFFFFF 0% 0% no-repeat padding-box',
                    border: '1px solid #1F343E',
                    borderRadius: '8px',
                  }}
                  id="outlined-adornment-weight"
                  startAdornment={
                    <InputAdornment position="end">
                      <img src="/assets/email.svg" alt="Email" />
                    </InputAdornment>
                  }
                  aria-describedby="outlined-weight-helper-text"
                  inputProps={{
                    'aria-label': 'weight',
                    sx: {
                      color: '#6D7A80',
                      pl: 2,
                      font: 'normal normal normal 20px/20px Noto Sans',
                    },
                  }}
                />
              </FormControl>
            </Grid>

            <Grid
              p={{ xs: 2, lg: 8 }}
              pt={0}
              container
              direction={'column'}
              justifyContent={'space-between'}>
              <Button
                sx={{
                  background: '#4EB3E3 0% 0% no-repeat padding-box',
                  border: '1px solid #1F343E',
                  borderRadius: '8px',
                  opacity: 1,
                  height: '64px',
                }}>
                <Typography
                  sx={{
                    font: 'normal normal bold 20px/32px Noto Sans',
                    textTransform: 'none',

                    color: '#FFFFFF',
                  }}>
                  Get Referral Link
                </Typography>
              </Button>
            </Grid>

            <Grid
              p={{ xs: 2, lg: 8 }}
              pt={6}
              mb={{ xs: 0, lg: 5 }}
              container
              direction={'column'}
              justifyContent={'space-between'}>
              <Typography
                sx={{
                  font: 'normal normal normal 16px/32px Noto Sans',
                  textTransform: 'none',

                  color: '#6D7A80',
                }}>
                Limits on max rewards apply.
              </Typography>
            </Grid>
          </Card>
        </Grid>
        <Grid item px={{ xs: 3, lg: 0 }} sx={{ justifyContent: 'center' }}>
          <Card
            sx={{
              m: { xs: 0, sm: 0, md: 8, lg: 8 },
              mt: { xs: 4, sm: 4, md: 0, lg: 10 },
              mb: { xs: 4, sm: 4, md: 8, lg: 8 },
              backgroundColor: '#F8CC5D',
              boxShadow: 'none',
              width: { lg: '544px', xs: 'auto' },
              height: { lg: '797px', xs: 'auto' },
            }}>
            <Grid container direction={'column'}>
              <Grid
                mt={{ xs: 2, lg: 10 }}
                container
                direction={'row'}
                sx={{ justifyContent: 'center' }}>
                <Grid item lg={4}>
                  <img src="/assets/invite.svg" alt="invite" />
                </Grid>
                <Grid
                  container
                  sx={{ justifyContent: { xs: 'center', lg: 'flex-start' } }}
                  direction={'row'}
                  item
                  lg={8}
                  xs={12}>
                  <Grid
                    item
                    mt={{ xs: 1.5, sm: 1.5, md: 0, lg: 0 }}
                    textAlign={{ xs: 'center', md: 'left' }}
                    xs={12}>
                    <Typography
                      sx={{
                        font: 'normal normal bold 16px/24px Gadugi',
                        textTransform: 'uppercase',
                        letterSpacing: '1.28px',
                        color: '#4EB3E3',
                      }}>
                      Step 1
                    </Typography>
                  </Grid>
                  <Grid
                    item
                    mt={{ xs: 1.5, sm: 1.5, md: 0, lg: 0 }}
                    textAlign={{ xs: 'center', md: 'left' }}
                    xs={12}>
                    <Typography
                      sx={{
                        font: 'normal normal normal 32px/40px Caveat Brush',
                        textTransform: 'uppercase',
                        letterSpacing: '0px',
                        color: '#1F343E',
                      }}>
                      INVITE FRIENDS{' '}
                    </Typography>
                  </Grid>
                  <Grid
                    item
                    mt={{ xs: 1.5, sm: 1.5, md: 0, lg: 0 }}
                    textAlign={{ xs: 'center', md: 'left' }}
                    lg={10}
                    xs={12}>
                    <Typography
                      sx={{
                        font: 'normal normal normal 16px/24px Noto Sans',
                        letterSpacing: '0px',
                        textTransform: 'none',
                        color: '#1F343E',
                      }}>
                      Refer friends with your unique referral link.
                    </Typography>
                  </Grid>
                </Grid>
              </Grid>

              <Grid
                mt={{ xs: 2, lg: 10 }}
                container
                direction={'row'}
                sx={{ justifyContent: 'center' }}>
                <Grid
                  mt={{ xs: 4, m: 4, md: 0, lg: 0 }}
                  item
                  lg={4}
                  sx={{ display: { xs: 'block', md: 'none' } }}>
                  <img src="/assets/collect-coins.svg" alt="coins" />
                </Grid>
                <Grid
                  container
                  sx={{ justifyContent: { xs: 'center', lg: 'flex-start' } }}
                  direction={'row'}
                  item
                  lg={8}
                  xs={12}>
                  <Grid
                    item
                    mt={{ xs: 1.5, sm: 1.5, md: 0, lg: 0 }}
                    textAlign={{ xs: 'center', md: 'left' }}
                    xs={12}>
                    <Typography
                      sx={{
                        font: 'normal normal bold 16px/24px Gadugi',
                        textTransform: 'uppercase',
                        letterSpacing: '1.28px',
                        color: '#4EB3E3',
                      }}>
                      Step 2
                    </Typography>
                  </Grid>
                  <Grid
                    item
                    mt={{ xs: 1.5, sm: 1.5, md: 0, lg: 0 }}
                    textAlign={{ xs: 'center', md: 'left' }}
                    xs={12}>
                    <Typography
                      sx={{
                        font: 'normal normal normal 32px/40px Caveat Brush',
                        textTransform: 'uppercase',
                        letterSpacing: '0px',
                        color: '#1F343E',
                      }}>
                      COLLECT COINS
                    </Typography>
                  </Grid>
                  <Grid
                    item
                    mt={{ xs: 1.5, sm: 1.5, md: 0, lg: 0 }}
                    textAlign={{ xs: 'center', md: 'left' }}
                    lg={10}
                    xs={12}>
                    <Typography
                      sx={{
                        font: 'normal normal normal 16px/24px Noto Sans',
                        letterSpacing: '0px',
                        textTransform: 'none',
                        color: '#1F343E',
                      }}>
                      Get 1 coin for each friend that installs our extension
                      using your referral link.
                    </Typography>
                  </Grid>
                </Grid>
                <Grid sx={{ display: { xs: 'none', md: 'block' } }} item lg={4}>
                  <img src="/assets/collect-coins.svg" alt="coins" />
                </Grid>
              </Grid>

              <Grid
                mt={{ xs: 2, lg: 10 }}
                container
                direction={'row'}
                sx={{ justifyContent: 'center' }}>
                <Grid item lg={4} mt={{ xs: 4, m: 4, md: 0, lg: 0 }}>
                  <img src="/assets/voucher.svg" alt="invite" />
                </Grid>
                <Grid
                  container
                  sx={{ justifyContent: { xs: 'center', lg: 'flex-start' } }}
                  direction={'row'}
                  item
                  lg={8}
                  xs={12}>
                  <Grid
                    item
                    mt={{ xs: 1.5, sm: 1.5, md: 0, lg: 0 }}
                    textAlign={{ xs: 'center', md: 'left' }}
                    xs={12}>
                    <Typography
                      sx={{
                        font: 'normal normal bold 16px/24px Gadugi',
                        textTransform: 'uppercase',
                        letterSpacing: '1.28px',
                        color: '#4EB3E3',
                      }}>
                      Step 3
                    </Typography>
                  </Grid>
                  <Grid
                    item
                    mt={{ xs: 1.5, sm: 1.5, md: 0, lg: 0 }}
                    textAlign={{ xs: 'center', md: 'left' }}
                    xs={12}>
                    <Typography
                      sx={{
                        font: 'normal normal normal 32px/40px Caveat Brush',
                        textTransform: 'uppercase',
                        letterSpacing: '0px',
                        color: '#1F343E',
                      }}>
                      GET VOUCHER
                    </Typography>
                  </Grid>
                  <Grid
                    item
                    mt={{ xs: 1.5, sm: 1.5, md: 0, lg: 0 }}
                    textAlign={{ xs: 'center', md: 'left' }}
                    lg={10}
                    xs={12}>
                    <Typography
                      sx={{
                        font: 'normal normal normal 16px/24px Noto Sans',
                        letterSpacing: '0px',
                        textTransform: 'none',
                        color: '#1F343E',
                      }}>
                      Redeem for a $20 hotel booking voucher once you collect 20
                      coins.
                    </Typography>
                  </Grid>
                </Grid>
              </Grid>
            </Grid>
          </Card>
        </Grid>
      </Grid>

      <Grid lg={12}>
        <Card
          sx={{
            py: { md: 3, xs: 2 },
            height: { xs: 'auto', lg: 'auto' },
            background: '#45565E 0% 0% no-repeat',
          }}>
          <Grid
            container
            direction={'row'}
            justifyContent={'center'}
            px={{ xs: 2, lg: 30 }}
            spacing={3}>
            <Grid item xs={12} lg={3.5} alignContent={'center'} mt={2}>
              <Box
                sx={{
                  background: '#45565E 0% 0% no-repeat padding-box',
                  border: '1px solid #1F343E',
                  borderRadius: 3,
                }}>
                <Grid container p={1}>
                  <Grid item px={{ xs: 2, md: 2 }}>
                    <img width={40} src="/assets/chrome.svg" alt="chrome" />
                  </Grid>
                  <Grid item pt={0.5}>
                    <Typography
                      sx={{
                        color: '#F8F4F9',
                        font: 'normal normal normal 16px/16px Noto Sans',
                      }}>
                      available in the
                    </Typography>

                    <Typography
                      sx={{
                        color: '#F8F4F9',
                        font: 'normal normal bold 20px/16px Gadugi',
                      }}>
                      chrome web store
                    </Typography>
                  </Grid>
                </Grid>
              </Box>
            </Grid>

            <Grid item xs={12} lg={3.5} alignContent={'center'} mt={2}>
              <Box
                sx={{
                  background: '#45565E 0% 0% no-repeat padding-box',
                  border: '1px solid #1F343E',
                  borderRadius: 3,
                }}>
                <Grid container p={1}>
                  <Grid item px={{ xs: 2, md: 3 }}>
                    <img
                      width={40}
                      src="/assets/apple.svg"
                      alt="Kitty Katty!"
                    />
                  </Grid>
                  <Grid item pt={0.5}>
                    <Typography
                      sx={{
                        color: '#F8F4F9',
                        font: 'normal normal normal 16px/16px Noto Sans',
                      }}>
                      available in the
                    </Typography>
                    <Typography
                      sx={{
                        color: '#F8F4F9',
                        font: 'normal normal bold 20px/16px Gadugi',
                      }}>
                      apple app store
                    </Typography>
                  </Grid>
                </Grid>
              </Box>
            </Grid>

            <Grid
              item
              container
              xs={12}
              lg={4}
              textAlign={'center'}
              alignContent={'center'}
              direction={'column'}
              mt={2.5}>
              <Grid textAlign={'center'} item>
                <Typography>
                  {' '}
                  <Rating value={5} sx={{ color: 'white' }}></Rating>
                </Typography>

                <Typography
                  textAlign={'center'}
                  sx={{ color: 'white' }}
                  display={'inline'}>
                  Chrome Store reviews{' '}
                </Typography>
              </Grid>
            </Grid>
          </Grid>
        </Card>
      </Grid>

      <Grid lg={12}>
        <Card
          sx={{
            height: { xs: 'auto', md: 400 },
            background: '#F8F4F9 0% 0% no-repeat padding-box',
            border: '1px solid #1F343E',
          }}>
          <Grid
            lg={4}
            xs={10}
            container
            sx={{ py: { xs: 3, md: 3 } }}
            justifyContent={'space-between'}
            mx={{ xs: 3, md: 30 }}>
            <Grid item sx={{}}>
              <Grid container direction={'column'}>
                <Grid item>
                  <img src="/assets/logo.svg" alt="Kitty Katty!" />
                </Grid>
                <Grid item pt={{ xs: 3, md: 10 }}>
                  <Typography
                    sx={{
                      color: '#1F343E',
                      font: 'normal normal normal 16px/24px Noto Sans',
                    }}>
                    {
                      'Ratepunk compares hotel room prices across the major online travel agencies. When you search for a room, Ratepunk extension scans the top booking sites and runs a price comparison, so you can be confident in knowing youre getting the best deal!'
                    }
                  </Typography>
                </Grid>
                <Grid item pt={{ xs: 5, md: 10 }}>
                  <Typography
                    sx={{
                      color: '#6D7A80',
                      font: 'normal normal normal 16px/24px Noto Sans',
                    }}>
                    {'© 2021 Ratepunk. All Rights Reserved.'}
                  </Typography>
                </Grid>
              </Grid>
            </Grid>
          </Grid>
        </Card>
      </Grid>
    </Grid>
  );
};

export default Home;
