import { Grid, styled } from '@mui/material';
import Head from 'next/head';

import Footer from '../src/components/footer';
import InfomaticsBox from '../src/components/infomaticsBox';
import ResponsiveNavBar from '../src/components/navbar';
import PluginStoreLinksBox from '../src/components/pluginStoreLinksBox';
import ReferralTextBox from '../src/components/referralTextBox';

import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <Grid sx={{ backgroundColor: '#F8CC5D' }}>
      <Head>
        <title>RatePunk Front End Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ResponsiveNavBar />
      <Grid container direction={'row'} justifyContent={'space-around'}>
        <Grid item>
          <ReferralTextBox />
        </Grid>
        <Grid item px={{ xs: 3, lg: 0 }} sx={{ justifyContent: 'center' }}>
          <InfomaticsBox />
        </Grid>
      </Grid>

      <Grid lg={12}>
        <PluginStoreLinksBox />
      </Grid>

      <Grid lg={12}>
        <Footer></Footer>
      </Grid>
    </Grid>
  );
};

export default Home;
